=== MartaOlive/TAPIS/schemas/nodeExtension_schema2.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "data attributes",
    "description": "'node' contains the internal description of the nodes by the vis.js library as well as some properties that help remember and propagate the meaning of the node in TAPIS",
	"type": "object",
	"properties": {
		"id": {
			"description": "Internal identifier of the node",
			"type": "string"
		},
		"label": {
			"description": "The label that acompanies the node shape",
			"type": "string"
		},
		"image": {
			"description": "Path to the image shown inside the shape",
			"type": "string",
			"format": "uri"
		},
		"shape": {
			"description": "Shape of the node",
			"enum": ["circularImage"]
		},
		"STAURL": {
			"description": "URL of the service or file represented as a table. Includes de path and query parameters",
			"type": "string",
			"format": "uri"
		},
		"STASelectedExpands": {
			"$ref": "#/definitions/selectedExpands"
		},
		"STAEntityName": {
			"description": "Last name of the entity in the path or expanded. Defines the scope of the node query parameters",
			"type": "string"
		},
		"STASelectExpandNextOrigin": {
			"description": "Points to the the recursive STASelectedExpands expanded entity that is the focus of the node query parameters. If empty, points to the root of STASelectedExpands",
			"type": "array",
			"items": {
				"description": "Index of the expand",
				"type": "integer"
			} 
		},
		"STAdata": {
			"$ref": "data_schema.json#/definitions/data"
		},
		"STAdataAttributes": {
			"$ref": "dataAttributes_schema.json#/definitions/dataAttributes"
		}
	},
	"definitions": { 
		"selectedExpands": {
			"type": "object",
			"properties": {
				"skip": {
					"description": "Number of entities to skip in the response. Default is 0", 
					"type": "integer"
				},				
				"top": {
					"description": "Number of entities to include in the response. Default is 100", 
					"type": "integer"
				},
				"orderBy": {
					"description": "Criteria to sort the entities in the response", 
					"type": "object",
					"properties": {
						"attribute": {
							"description": "Name of the attribute that is used to sort the data", 
							"type": "string"
						},
						"desc": {
							"description": "Way to sort the data. true mean descending. false mean ascending", 
							"type": "boolean"
						}
					}
				},
				"selected": {
					"description": "Attributes selected to be included in the returned entities. If missing, all attributes are included. The implementation also supports an object with additionalProperties that are booleans for historical reasons.", 
					"type": "array",
					"items": {
						"description": "Attribute name", 
						"type": "string"
					}
				},
				"expanded": {
					"type": "object",
					"additionalProperties": { 
						"description": "Name of the entity to be expanded as a JSON object in the response",
						"$ref": "#/definitions/selectedExpands"
					}
				},
				"STAFilter":{
					"type": "object",
					"description": "Schema and data to built filter query", 
					"properties": { 
						"entity":{
							"description": "Entity where the filter will be applied", 
							"type": "string"
						},
						"filterSchema":{
							"description": "Scheme to be able to set filter priorities", 
							"type": "object"
						},
						"filterData":{
							"description": "The information to form the filter, such as entities, properties, conditions and values", 
							"type": "array"
						}
					}
				}
			}
		}
	}
}

=== MartaOlive/TAPIS/schemas/nodeExtension_example.json
{
    "id": "57opt.4g8l04",
    "label": "Merge Expands",
    "image": "MergeExpandsSTA.png",
    "shape": "circularImage",
    "STAURL": "https://citiobs.demo.secure-dimensions.de/staplustest/v1.1/Things?$expand=HistoricalLocations($top=5;$orderby=time desc),Datastreams($top=2)",
    "STASelectedExpands": {
        "selected": [],
        "expanded": {
            "HistoricalLocations": {
                "selected": ["time"],
                "expanded": {},
                "skip": 0,
                "top": 5,
                "orderBy": {
                    "attribute": "time",
                    "desc": true
                }
            },
            "Datastreams": {
                "selected": [],
                "expanded": {},
                "skip": 0,
                "top": 2,
                "filter": {
                    "entity": "Datastreams",
                    "filterSchema": {
                        "0_0": {
                            "items": [
                                0,
                                1
                            ],
                            "nexus": " or "
                        }
                    },
                    "filterData": [
                        [
                            0,
                            "Datastreams",
                            [
                                "name"
                            ],
                            " = ",
                            "Air Temperature",
                            "text"
                        ],
                        [
                            1,
                            "Datastreams",
                            [
                                "name"
                            ],
                            " = ",
                            "Noise Level",
                            "text"
                        ]
                    ]
                }
            }
        }
    },
    "STAEntityName": "Things",
    "STASelectExpandNextOrigin": [],
    "STAdata": [
    ],
    "STAdataAttributes": {
        "@iot.selfLink": {
            "type": "anyURI",
            "definition": "http://www.opengis.net/def/docs/15-078r6/Thing/@iot.selfLink"
        },
        "@iot.id": {
            "type": "integer",
            "definition": "http://www.opengis.net/def/docs/15-078r6/Thing/@iot.id"
        },
        "name": {
            "type": "string",
            "definition": "http://www.opengis.net/def/docs/15-078r6/Thing/name"
        },
        "description": {
            "type": "string",
            "definition": "http://www.opengis.net/def/docs/15-078r6/Thing/description"
        },
        "properties": {
            "type": "object",
            "definition": "http://www.opengis.net/def/docs/15-078r6/Thing/properties"
        },
        "HistoricalLocations": {
            "type": "array",
            "definition": "http://www.opengis.net/def/docs/15-078r6/Thing/HistoricalLocations"
        },
        "HistoricalLocations@iot.nextLink": {
            "type": "string",
            "definition": "http://www.opengis.net/def/docs/15-078r6/Thing/HistoricalLocations@iot.nextLink"
        },
        "Datastreams": {
            "type": "array",
            "definition": "http://www.opengis.net/def/docs/15-078r6/Thing/Datastreams"
        },
        "Datastreams@iot.nextLink": {
            "type": "string",
            "definition": "http://www.opengis.net/def/docs/15-078r6/Thing/Datastreams@iot.nextLink"
        },
        "Party@iot.navigationLink": {
            "type": "anyURI",
            "definition": "http://www.opengis.net/def/docs/15-078r6/Thing/Party@iot.navigationLink"
        },
        "HistoricalLocations@iot.navigationLink": {
            "type": "anyURI",
            "definition": "http://www.opengis.net/def/docs/15-078r6/Thing/HistoricalLocations@iot.navigationLink"
        },
        "Locations@iot.navigationLink": {
            "type": "anyURI",
            "definition": "http://www.opengis.net/def/docs/15-078r6/Thing/Locations@iot.navigationLink"
        },
        "MultiDatastreams@iot.navigationLink": {
            "type": "anyURI",
            "definition": "http://www.opengis.net/def/docs/15-078r6/Thing/MultiDatastreams@iot.navigationLink"
        },
        "Datastreams@iot.navigationLink": {
            "type": "anyURI",
            "definition": "http://www.opengis.net/def/docs/15-078r6/Thing/Datastreams@iot.navigationLink"
        }
    }
}
